# Generated by Django 4.0.6 on 2022-08-15 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_personas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('pais', models.CharField(max_length=150)),
                ('municipio', models.CharField(max_length=150)),
            ],
        ),
    ]
